/// Flutter icons TropiIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TropiIcons
///      fonts:
///       - asset: fonts/TropiIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class TropiIcons {
  TropiIcons._();

  static const _kFontFam = 'TropiIcons';
  static const _kFontPkg = null;

  static const IconData favorite_border = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData corazon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cocina = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData correo = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idea = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
